spring:
  application:
    name: zuul-server

server:
  port: 50000
  
logging:
  file: ./logs/zuul-server.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka2017@10.0.0.219:1111/eureka/
  instance:
    prefer-ip-address: true
    non-secure-port: "${server.port}"

zuul:
  routes:
    tms:
      path: /tms/**
      serviceId: task-management-server
      customSensitiveHeaders: true
    dms:
      path: /dms/**
      serviceId: datasource-management-server
    dds:
      path: /dds/**
      serviceId: data-desensitive-server
  ws:
    brokerages:
      tms:
        end-points: /endpointChat
        brokers:  /topic
        destination-prefixes: /

